export const primaryColor = "#007BA7";
export const lightPrimaryColor = "#50B2EA";
export const extraLPrimaryColor = "#D3EBF9"; 
export const secondaryColor = "#FF4500";
export const lightSecondaryColor = "#F96027";
export const extraLSecondaryColor = "#FDC9B6"; 
export const tertiaryColor = "#98FF98";
export const mainHeading = "600 38px/30px Raleway, serif";
export const mainSubHeading = "600 30px/30px Raleway, serif";
